### PR TITLE
Add CFunc::libcall. For windows, function call require dll name.

### PR DESCRIPTION
**Pull request by mattn**
https://twitter.com/mattn_jp/statuses/294386160338358272

これをやろうと思うと、dll名称を渡す必要があったので追加しました。

### CODE REVIEW

**Comment by mattn** [comment]
ちなみに、これが出来るとあとは自分で LoadLibraryA → GetProcAddress として関数コールできるはずです。

**Comment by mattn** [comment]
良く考えたらこれclass_methodじゃなくてmodule_functionですね。

**Comment by ppibburr** [comment]
this is useful in linux as well. example,
mruby-girffi was doing this in the ruby code. but the c version is better

**Comment by masuidrive** [comment]
@mattn Could you add tests?

**Comment by mattn** [comment]
For adding test, we can decide which library is possible to load from tests.
- create shared library it self?
- or load OS specific library? (But mruby can't recognize OSs)

**Comment by mattn** [comment]
``` ruby
if mruby_running_on_win32
  create_dll_file()
  CFunc.libcall("foo.dll", ...)
else
  create_so_file()
  CFunc.libcall("foo.so", ...)
end
```

Or

``` ruby
if mruby_running_on_win32
  create_dll_file()
  CFunc.libcall("user32.dll", ...)
else
  create_so_file()
  CFunc.libcall("/lib/libc.so", ...)
end
```

**Comment by masuidrive** [comment]
Could you add CFunc.platform?

**Comment by mattn** [comment]
It's possible but not easy.

**Comment by mattn** [comment]
Below is a values which is possible to be in RUBY_PLATFORM.

```
alpha-freebsd
alpha-linux
alpha-netbsd
alpha-osf
alphaev56-linux
alphaev56-osf
alphaev6-linux
alphaev6-osf
alphaev67-osf
arm-linux
hppa1.1-hpux
hppa2.0-hpux
hppa2.0n-hpux
hppa2.0w-hpux
ix86-bccwin32
ix86-beos
ix86-bsdi
ix86-cygwin
ix86-freebsd
ix86-linux
ix86-mingw32
ix86-msdosdjgpp
ix86-mswin32
ix86-netbsd
ix86-openbsd
ix86-os2_emx
ix86-solaris
ix86-sysv5
m68k-linux
mips-irix
mips-sysv
mipsel-linux
powerpc-aix
powerpc-darwin
powerpc-linux
rs6000-aix
s390-linux
sparc-linux
sparc-netbsd
sparc-solaris
sparc-sunos
sparc-uxpds
sparc64-linux
x86-nto-qnx
```

**Comment by masuidrive** [comment]
I think it's too much too.
libffi supported platforms in http://sourceware.org/libffi/

How does that sound?
- CFunc::Plafform.is_posix?, is_win32?

**Comment by mattn** [comment]
BTW, do you know the function that is callable dynamically on OS X?
For example, on linux, `sin` in `/usr/lib/libm.so`.

**Comment by mattn** [comment]
once, close this to create new one.

**Comment by masuidrive** [comment]
/usr/lib/libm.dylib has open in OSX.

**Comment by mattn** [comment]
`open` leave un-handled files if test failed. how about `sin` or `cos` ?

**Comment by mattn** [comment]
OSX has `*.dylib` but linux has `*.so`. `is_mac?` is needed? hehe...

**Pull request closed without merging**
