### PR TITLE
Ruby FFI compatibility layer

### PR DESCRIPTION
**Pull request by schmurfy**
The code is ready to be merged but there is one thing to take car of before that:
how to add a proper way to set the location of includes/library ? (I had to hardcode mine in mrbgems.rake)

I started by extracting the abstraction in mruby-girffi and from there found multiple issues I fixed as well as missing apis or incorrect method signature, in its current state I have a yet to release gem taking advantage of this abstraction to make it works both as a mruby gem and as a mri gem which was my original goal.

I made sure a large part of the ruby ffi interface was implemented but not everything is of course but apis can be added as needed later.

### CODE REVIEW

**Comment by masuidrive** [comment]
Thank you for sending pull request!
I'll review and reply within 2-3 days.

**Comment by schmurfy** [comment]
did you got time to check it ?
I can also release it as a separate gem if you prefer.

If you are wondering what I use it for you can look at https://github.com/schmurfy/host-stats, this is still a work in progress but it is already useable with both MRI ruby and mruby.

**Comment by schmurfy** [comment]
rebased on master.

**Comment by masuidrive** [comment]
Sorry for big delay. I'll review in weekend.

**Comment by schmurfy** [comment]
ok, thanks :)

**Comment by ppibburr** [comment]
@schmurfy Would you make a gem? mruby-girffi was meant to be a layer above FFI Compat, never got around to separation or API complete/accuracy. I'd like the girffi code base to run on mri and mruby.

**Comment by schmurfy** [comment]
That's what i was going to do, I will check that this week end. Having gems compatible with both mruby and standard is also the reason I needed the abstraction.

**Comment by ppibburr** [comment]
Good to hear! i'm testing host-stats.

**Comment by schmurfy** [comment]
@masuidrive I decided to create a separate project for the compatibility layer, it will be easier to manage and now that we can define dependencies between gems it will also help.

I created some easier to review pull requests for the small changes I need for either this new gem or host-stats.

**Comment by schmurfy** [comment]
If anyone is interested the gem is now here:
https://github.com/schmurfy/mruby-rubyffi-compat

**Pull request closed without merging**
